import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/71lYhcc++AL._AC_UY218_.jpg",
    title: "ASUS VivoBook 15",
    star: <AiFillStar className="rating-star" />,
    reviews: "(124 reviews)",
    prevPrice: "₹33900",
    newPrice: "19900",
    company: "Asus",
    color: "grey",
    category: "Laptop",
    description:"VivoBook 15 (2021), 15.6-inch (39.62 cm) HD, Dual Core Intel Celeron N4020, Thin and Light Laptop (4GB)"
  },
  {
    img: "https://m.media-amazon.com/images/I/616TNXcZcHL._AC_UY218_.jpg",
    title: "ASUS TUF Gaming F15",
    star: <AiFillStar className="rating-star" />,
    reviews: "(200 reviews)",
    prevPrice: "₹75000",
    newPrice: "49900",
    company: "Asus",
    color: "black",
    category: "Laptop",
    description:"TUF Gaming F15 - AI Powered Gaming Laptop, Intel Core i5-11400H 11th Gen, 15.6-inch (39.62 cm) FHD 144Hz,"
  },

  {
    img: "https://m.media-amazon.com/images/I/71-Fx3Vfq5L._AC_UY218_.jpg",
    title: "ASUS VivoBook 15",
    star: <AiFillStar className="rating-star" />,
    reviews: "(250 reviews)",
    prevPrice: "₹65000",
    newPrice: "30900",
    company: "Asus",
    color: "black",
    category: "Laptop",
    description:"VivoBook 15, Intel Core i3-1115G4 11th Gen, 15.6 (39.62 cm) FHD, Thin and Light Laptop (8GB/512 SSD/Windows)"
  },
  {
    img: "https://m.media-amazon.com/images/I/71yejFYehdL._AC_UY218_.jpg",
    title: "ASUS Zenbook 14X OLED",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹89000",
    newPrice: "67900",
    company: "Asus",
    color: "black",
    category: "Laptop",
    description:"Zenbook 14X OLED, Intel Core i5-12500H 12th Gen, 14 (35.56 cm) 2.8K 90Hz OLED, Thin and Light Laptop)"
  },
  {
    img: "https://m.media-amazon.com/images/I/71qTbS09tjL._AC_UY218_.jpg",
    title: "ASUS Vivobook 14",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹75000",
    newPrice: "49900",
    company: "Asus",
    color: "black",
    category: "Laptop",
    description:"Vivobook 14, IntelCore i3-1215U 12th Gen, 14(35.56 cm) FHD, Thin and Light Laptop (8 GB RAM/512GB"
  },
  {
    img: "https://m.media-amazon.com/images/I/81UWgnVKDBL._AC_UY218_.jpg",
    title: "ASUS Vivobook 14, IntelCore i3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹85000",
    newPrice: "50000",
    company: "Asus",
    color: "grey",
    category: "Laptop",
    description:"Vivobook 14, IntelCore i3-1215U 12th Gen, 14 (35.56 cm) FHD, Thin and Light Laptop (8 GB RAM/512GB)"
  },

  {
    img: "https://m.media-amazon.com/images/I/71KXxVGeMVL._AC_UY218_.jpg",
    title: "ASUS Creator Series Vivobook",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹70000",
    newPrice: "59900",
    company: "Asus",
    color: "grey",
    category: "Laptop",
    description:"Creator Series Vivobook 14X OLED 2023, Intel Core i5-12450H 12th Gen, 14.0-inch 90Hz, Laptop (16GB/512GB)"
  },

  {
    img: "https://m.media-amazon.com/images/I/71qTbS09tjL._AC_UY218_.jpg",
    title: "ASUS Vivobook S 15 OLED (2023)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹75000",
    newPrice: "49900",
    company: "Asus",
    color: "black",
    category: "Laptop",
    description:"Vivobook S 15 OLED (2023), Intel Core EVO i9-13900H 13th Gen, 15.6 (39.62 cm) 2.8K 120Hz OLED, Thin & Light"
  },

  {
    img: "https://m.media-amazon.com/images/I/71c0GSxtEEL._AC_UY218_.jpg",
    title: "ASUS Vivobook 16X (2022), AMD Ryzen 7",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Asus",
    color: "black",
    category: "Laptop",
    description:"Vivobook 16X (2022), AMD Ryzen 7 5800Hs, 16(40.64 Cms) Fhd+, Thin and Laptop (HDMI/16Gb/512Gb Ssd/Windows 11/Office 2021/Alexa Built-in/Backlit Kb/Fp Sensor/Silver/1.88 Kg), M1603Qa-Mb712Ws4.4 out of 5 stars"
  },

  {
    img: "https://m.media-amazon.com/images/I/51xp803KbNL._AC_UY218_.jpg",
    title: "Dell 14 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹65000",
    newPrice: "54900",
    company: "Dell",
    color: "black",
    category: "Laptop",
    description:"Dell 14 Laptop, 12th Gen Intel Core i5-1235U Processor, 16GB, 512GB, 14.0 (35.56cm) FHD Display, Windows 11 )"
  },
  {
    img: "https://m.media-amazon.com/images/I/61TJSzvEsQL._AC_UY218_.jpg",
    title: "Dell 15 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Dell",
    color: "black",
    category: "Laptop",
    description:"Dell 15 Laptop, 13th Gen Intel Core i5-1335U Processor/ 8GB/ 512GB SSD/15.6(39.62cm) FHD AG 120Hz 250 nits Narrow Borde..."
   },
  {
    img: "https://m.media-amazon.com/images/I/61-9M-wUoAL._AC_UY218_.jpg",
    title: " Dell G15 5530 Gaming Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Dell",
    color: "black",
    category: "Laptop",
    description:"G15 5530 Gaming Laptop, Intel i9-13900HX, 16GB DDR5, 1TB SSD, NVIDIA RTX 4060-8GB GDDR6, 15.6"
  },
  {
    img: "https://m.media-amazon.com/images/I/51O5DuikX4L._AC_UY218_.jpg",
    title: "Dell Inspiron 3520 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Dell",
    color: "black",
    category: "Laptop",
    description:"Inspiron 3520 Laptop, 12th Gen Intel Core i5-1235U Processor, 8GB, 512GB SSD, 15.6 (39.62Cms)"
  },
  {
    img: "https://m.media-amazon.com/images/I/51Zl9TAM8kL._AC_UY218_.jpg",
    title: "Dell Inspiron 3511 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Dell",
    color: "black",
    category: "Laptop",
    description:"Inspiron 3511 Laptop, Intel Core I5-1135G7 Processor/ 8GB/ 512GB SSD/ 15.6 (39.62cm) FHD Display/Backlite)"
  },

  {
    img: "https://m.media-amazon.com/images/I/51NvEfo1l9L._AC_UY218_.jpg",
    title: "Lenovo Ideapad Slim 3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Lenovo",
    color: "grey",
    category: "Laptop",
    description:"Lenovo Ideapad Slim 3 Ryzen 5 7520U 15.6 (39.6Cm) Fhd Laptop (16Gb/512Gb Ssd/Win 11/Office 2021/1 Year Warranty/Alexa Built-in/3 Month Game Pass/Arctic Grey/1.62Kg), 82Xq008Vin, AMD3.9 out of 5 stars"
  },
  {
    img: "https://m.media-amazon.com/images/I/61y4yt0L2oL._AC_UY218_.jpg",
    title: "Lenovo laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹45000",
    newPrice: "19900",
    company: "Lenovo",
    color: "black",
    category: "Laptop",
    description:"E41-55 AMD 14-inch HD 220 Nits Antiglare Thin and Light Laptop (AMD Athlon A3050U/4GB RAM/256GB)"
  },
  {
    img: "https://m.media-amazon.com/images/I/61PeZXpc5-L._AC_UY218_.jpg",
    title: "Lenevo Ideapad",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Lenovo",
    color: "black",
    category: "Laptop",
    description:"Smartchoice] Lenovo Ideapad 3 11Th Gen Intel Core I3 15.6 Fhd Thin & Light Laptop(8Gb/512Gb Ssd/Window"
  },
  {
    img: "https://m.media-amazon.com/images/I/61jyqpkeJQL._AC_UY218_.jpg",
    title: "Lenevo Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "39900",
    company: "Lenovo",
    color: "grey",
    category: "Laptop",
    description:"Smartchoice] Lenovo Ideapad 3 11Th Gen Intel Core I3 15.6 Fhd Thin & Light Laptop(8Gb/512Gb Ssd/Window)"
  },
  {
    img: "https://m.media-amazon.com/images/I/71VzT-eg0tL._AC_UY218_.jpg",
    title: "Hp Laptop15",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹73000",
    newPrice: "59900",
    company: "Hp",
    color: "grey",
    category: "Laptop",
    description:"Laptop 15, 13th Gen Intel Core i5-1335U, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, Intel Iris Xe Graphics)"
  },
  {
    img: "https://m.media-amazon.com/images/I/71wa5QWCfML._AC_UY218_.jpg",
    title: "Hp Gaming Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Hp",
    color: "black",
    category: "Laptop",
    description:"Victus Gaming Laptop,11Th Gen Intel Core I5-11400H,Nvidia GTX 1650 Gpu,16.1-in"
  },
  {
    img: "https://m.media-amazon.com/images/I/81m1tlvW3bL._AC_UY218_.jpg",
    title: "Hp laptop 15",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹71000",
    newPrice: "53900",
    company: "Hp",
    color: "grey",
    category: "Laptop",
    description:"HP Laptop 15s, 12th Gen Intel Core i5-1235U, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, Intel UHD Graphics, Backlit K..."
     },
  {
    img: "https://m.media-amazon.com/images/I/71wa5QWCfML._AC_UY218_.jpg",
    title: "Dell 14 laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹65000",
    newPrice: "37900",
    company: "Dell",
    color: "black",
    category: "Laptop",
    description:"14 Laptop, Intel Core i5-1135G7 Processor/8GB/512GB/Intel UHD Graphic/14.0 (35.6cm)"
  },
  {
    img: "https://m.media-amazon.com/images/I/71NKq8zV8ML._AC_UY218_.jpg",
    title: "Acer Aspire lite Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "49900",
    company: "Acer",
    color: "black",
    category: "Laptop",
    description:"One 14 AMD Ryzen 3 3250U Processor (8GB RAM/512GB SSD/AMD Radeon Graphics/Windows 11 Home) "
  },

  {
    img: "https://m.media-amazon.com/images/I/71NKq8zV8ML._AC_UY218_.jpg",
    title: "Acer One 14 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Acer",
    color: "black",
    category: "Laptop",
    description:"One 14 AMD Ryzen 3 3250U Processor (8GB RAM/512GB SSD/AMD Radeon Graphics/Windows 11 Home) "
  },
  {
    img: "https://m.media-amazon.com/images/I/71czGb00k5L._AC_UY218_.jpg",
    title: "Acer Laptop One 14 AMD Ryzen 3 ",
    reviews: "(128 reviews)",
    prevPrice: "₹65000",
    newPrice: "59900",
    company: "Acer",
    color: "black",
    category: "Laptop",
    description:"One 14 AMD Ryzen 3 3250U Processor (8GB RAM/512GB SSD/AMD Radeon Graphics/Windows 11 Home) "
  },
  {
    img: "https://m.media-amazon.com/images/I/71NKq8zV8ML._AC_UY218_.jpg",
    title: "Acer Aspire 5 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Acer",
    color: "black",
    category: "Laptop",
    description:"Aspire 5 AMD Ryzen 3 3250U Processor (8GB RAM/512GB SSD/AMD Radeon Graphics/Windows 11 Home) "
  },
  {
    img: "https://m.media-amazon.com/images/I/71czGb00k5L._AC_UY218_.jpg",
    title: "Acer Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "69900",
    company: "Acer",
    color: "black",
    category: "Laptop",
    description:"One 15 AMD Ryzen 3 3250U Processor (8GB RAM/512GB SSD/AMD Radeon Graphics/Windows 11 Home) "
  },
  {
    img: "https://m.media-amazon.com/images/I/71S4sIPFvBL._AC_UY218_.jpg",
    title: "Acer 12 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Acer",
    color: "black",
    category: "Laptop",
    description:"Acer 12 AMD Ryzen 7 3250U Processor (8GB RAM/512GB SSD/AMD Radeon Graphics/Windows 11 Home) "
  },
  {
    img: "https://m.media-amazon.com/images/I/71czGb00k5L._AC_UY218_.jpg",
    title: "Acer aspire 5 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹75000",
    newPrice: "59900",
    company: "Acer",
    color: "black",
    category: "Laptop",
    description:"Aspire 5 AMD Ryzen 3 3250U Processor (8GB RAM/512GB SSD/AMD Radeon Graphics/Windows 11 Home) "
  },
  {
    img: "https://m.media-amazon.com/images/I/71S4sIPFvBL._AC_UY218_.jpg",
    title: "Apple Macbook 2023",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹175000",
    newPrice: "159900",
    company: "Apple",
    color: "black",
    category: "Laptop",
    description:"2023 MacBook Air Laptop with M2 chip: 38.91 cm (15.3 inch) Liquid Retina Display, 8GB RAM 512GB SSD"
  },
  {
    img: "https://m.media-amazon.com/images/I/71eXNIDUGjL._AC_UY218_.jpg",
    title: "Apple Macbook 2022",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹175000",
    newPrice: "169900",
    company: "Apple",
    color: "black",
    category: "Laptop",
    description:"2022 MacBook Air Laptop with M2 chip: 38.91 cm (15.3 inch) Liquid Retina Display, 8GB RAM 512GB SSD"
  },
  {
    img: "https://m.media-amazon.com/images/I/618d5bS2lUL._AC_UY218_.jpg",
    title: "Apple Macbook 2023",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹205000",
    newPrice: "179900",
    company: "Apple",
    color: "black",
    category: "Laptop",
    description:"2023 MacBook Pro (16-inch, M3 Max chip with 14‑core CPU and 30‑core GPU, 36GB Unified Memory, 1TB)"
  },
  {
    img: "https://m.media-amazon.com/images/I/71S4sIPFvBL._AC_UY218_.jpg",
    title: "Apple Macbook 2023",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹205000",
    newPrice: "129900",
    company: "Apple",
    color: "black",
    category: "Laptop",
    description:"2023 MacBook Air Laptop with M2 chip: 38.91 cm (15.3 inch) Liquid Retina Display, 8GB RAM 512GB SSD Storage"
  },
  {
    img: "https://m.media-amazon.com/images/I/71eXNIDUGjL._AC_UY218_.jpg",
    title: "Apple Macbook 2023",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹205000",
    newPrice: "139900",
    company: "Apple",
    color: "black",
    category: "Laptop",
    description:"Apple 2023 MacBook Pro (14-inch, M3 chip with 8‑core CPU and 10‑core GPU, 8GB Unified Memory, 512GB) - Silver"
    },
  {
    img: "https://m.media-amazon.com/images/I/618d5bS2lUL._AC_UY218_.jpg",
    title: "Apple Macbook 2022 pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "₹205000",
    newPrice: "149900",
    company: "Apple",
    color: "black",
    category: "Laptop",
    description:"Apple 2022 MacBook Pro (14-inch, M3 chip with 8‑core CPU and 10‑core GPU, 8GB Unified Memory, 512GB) - Silver"
    },
]
export default data;